# Generated by Django 6.0.3 on 2026-03-08 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_found', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/', verbose_name='item_image')),
                ('status', models.CharField(choices=[('claimed', 'Claimed'), ('not_claimed', 'Not Claimed')])),
                ('found_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
