# Generated by Django 6.0.3 on 2026-03-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('claimed', 'Claimed'), ('not_claimed', 'Not Claimed')], default='not_claimed'),
        ),
    ]
