# Generated by Django 6.0.3 on 2026-03-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='post_type',
            field=models.CharField(choices=[('lost', 'Lost Post'), ('found', 'Found Post')], default='lost', max_length=10),
        ),
    ]
